language: erlang

before_script:
    - "./travis-ci-setup -h127.0.0.1 -utravis"
    - make

# once #89 is closed, this should be replaced by 'make all-test'
script: "make test"
otp_release:
   - R16B
   - R15B03
   - R15B02
   - R15B01
   - R15B
   - R14B04
   - R14B03
   - R14B02
